/**
 * S2.3 — every user-visible Support Agent reply, per locale. The model never
 * writes these; `renderSupportReply` fills `{slots}` from the lookup payload.
 * Money slots arrive pre-formatted (the surface renders paise); dates arrive as
 * the surface formats them. Status labels reuse the app's own `orders.status_*`
 * / `rfq.status_*` English and Hindi text so the agent never contradicts the
 * app (te / ta added here; the app has no te / ta labels yet).
 */
import type { SupportLocale, SupportReplyKey } from './support'

export const ORDER_STATUS_LABELS: Record<SupportLocale, Record<string, string>> = {
  en: { placed: 'Placed', accepted: 'Accepted', requirements_submitted: 'Requirements submitted', in_progress: 'In progress', delivered: 'Delivered', revision_requested: 'Revision requested', completed: 'Completed', reviewed: 'Reviewed', disputed: 'Disputed', resolved_refund: 'Resolved (refund)', resolved_release: 'Resolved (released)', resolved_partial: 'Resolved (partial refund)', refunded: 'Refunded', auto_cancelled: 'Auto-cancelled', cancelled_by_buyer: 'Cancelled', cancelled_duplicate: 'Cancelled (duplicate payment)' },
  hi: { placed: 'दिया गया', accepted: 'स्वीकृत', requirements_submitted: 'आवश्यकताएं जमा', in_progress: 'प्रगति में', delivered: 'डिलीवर किया गया', revision_requested: 'संशोधन अनुरोध', completed: 'पूर्ण', reviewed: 'समीक्षित', disputed: 'विवादित', resolved_refund: 'निपटा (रिफंड)', resolved_release: 'निपटा (जारी)', resolved_partial: 'निपटा (आंशिक रिफंड)', refunded: 'वापस किया गया', auto_cancelled: 'स्वतः रद्द', cancelled_by_buyer: 'रद्द किया गया', cancelled_duplicate: 'रद्द (दोहरा भुगतान)' },
  te: { placed: 'ఆర్డర్ ఇచ్చారు', accepted: 'ఆమోదించారు', requirements_submitted: 'అవసరాలు సమర్పించారు', in_progress: 'పనిలో ఉంది', delivered: 'డెలివరీ అయింది', revision_requested: 'సవరణ కోరారు', completed: 'పూర్తయింది', reviewed: 'సమీక్షించారు', disputed: 'వివాదంలో', resolved_refund: 'పరిష్కారం (రీఫండ్)', resolved_release: 'పరిష్కారం (విడుదల)', resolved_partial: 'పరిష్కారం (పాక్షిక రీఫండ్)', refunded: 'రీఫండ్ అయింది', auto_cancelled: 'ఆటో రద్దు', cancelled_by_buyer: 'రద్దు అయింది', cancelled_duplicate: 'రద్దు (రెండుసార్లు చెల్లింపు)' },
  ta: { placed: 'ஆர்டர் செய்யப்பட்டது', accepted: 'ஏற்கப்பட்டது', requirements_submitted: 'தேவைகள் சமர்ப்பிக்கப்பட்டன', in_progress: 'நடைபெறுகிறது', delivered: 'டெலிவரி ஆனது', revision_requested: 'திருத்தம் கோரப்பட்டது', completed: 'முடிந்தது', reviewed: 'மதிப்பாய்வு செய்யப்பட்டது', disputed: 'சர்ச்சையில்', resolved_refund: 'தீர்வு (திரும்பப் பணம்)', resolved_release: 'தீர்வு (விடுவிப்பு)', resolved_partial: 'தீர்வு (பகுதி திரும்பப் பணம்)', refunded: 'திரும்பப் பணம் ஆனது', auto_cancelled: 'தானாக ரத்து', cancelled_by_buyer: 'ரத்து ஆனது', cancelled_duplicate: 'ரத்து (இருமுறை செலுத்தியது)' },
}

export const RFQ_STATUS_LABELS: Record<SupportLocale, Record<string, string>> = {
  en: { open: 'Open', quoted: 'Receiving quotes', accepted: 'Accepted', expired: 'Expired', cancelled: 'Cancelled' },
  hi: { open: 'खुला', quoted: 'कोटेशन मिल रहे हैं', accepted: 'स्वीकृत', expired: 'समाप्त', cancelled: 'रद्द' },
  te: { open: 'తెరిచి ఉంది', quoted: 'కొటేషన్లు వస్తున్నాయి', accepted: 'ఆమోదించారు', expired: 'గడువు ముగిసింది', cancelled: 'రద్దు' },
  ta: { open: 'திறந்துள்ளது', quoted: 'விலைப்புள்ளிகள் வருகின்றன', accepted: 'ஏற்கப்பட்டது', expired: 'காலாவதி', cancelled: 'ரத்து' },
}

export const PAYOUT_STATUS_LABELS: Record<SupportLocale, Record<string, string>> = {
  en: { scheduled: 'Scheduled', processing: 'Processing', paid: 'Paid', failed: 'Failed (retrying)', held: 'On hold' },
  hi: { scheduled: 'निर्धारित', processing: 'प्रोसेस हो रहा', paid: 'भुगतान हुआ', failed: 'विफल (पुनः प्रयास)', held: 'रोका गया' },
  te: { scheduled: 'షెడ్యూల్ అయింది', processing: 'ప్రాసెస్ అవుతోంది', paid: 'చెల్లించారు', failed: 'విఫలం (మళ్లీ ప్రయత్నం)', held: 'నిలిపివేశారు' },
  ta: { scheduled: 'திட்டமிடப்பட்டது', processing: 'செயலாக்கத்தில்', paid: 'செலுத்தப்பட்டது', failed: 'தோல்வி (மீண்டும் முயற்சி)', held: 'நிறுத்தி வைக்கப்பட்டது' },
}

type Copy = Record<SupportReplyKey, string>

const en: Copy = {
  'order_status.placed': 'Order {order_number} ({title}) is placed and paid. The provider has up to 24 hours to accept; if they do not, it is cancelled and refunded in full.',
  'order_status.accepted': 'Order {order_number} ({title}) is accepted. The provider is waiting for your requirements, or will start shortly. Expected by {eta_date}.',
  'order_status.requirements_submitted': 'Order {order_number} ({title}): requirements received; the provider is about to start. Expected by {eta_date}.',
  'order_status.in_progress': 'Order {order_number} ({title}) is in progress. Expected by {eta_date}. Your payment ({amount}) stays with AMClub until you accept the work.',
  'order_status.delivered': 'Order {order_number} ({title}) is delivered. Please review the work: accept it, or request a revision. It auto-completes 72 hours after delivery if you do nothing.',
  'order_status.revision_requested': 'Order {order_number} ({title}): a revision is requested and the provider is working on it.',
  'order_status.completed': 'Order {order_number} ({title}) is completed. {amount} is released to the provider per the payout schedule.',
  'order_status.reviewed': 'Order {order_number} ({title}) is completed and reviewed. Thank you.',
  'order_status.disputed': 'Order {order_number} ({title}) is under dispute. Our team reviews both sides; we acknowledge within {sla_hours} hours and resolve within {sla_days} days.',
  'order_status.resolved': 'Order {order_number} ({title}) is resolved: {status_label}. Any refund reaches you within 5–7 working days.',
  'order_status.cancelled': 'Order {order_number} ({title}) is cancelled ({status_label}). Any refund reaches you within 5–7 working days.',
  'order_status.refunded': 'Order {order_number} ({title}) is refunded. The amount ({amount}) reaches your account within 5–7 working days.',
  'order_status.not_found': 'I could not find that order under your account. Please share the order number as it appears in your orders list.',
  'order_status.none': 'You have no orders yet. Post a request or buy a package and it will appear here.',
  'quote_status.submitted': 'Your quote ({price}) on "{title}" is submitted and visible to the buyer. The request has {quote_count} of {max_quotes} quotes; it expires on {expires_date}.',
  'quote_status.accepted': 'Your quote on "{title}" was accepted — the order is on your orders list.',
  'quote_status.declined': 'Your quote on "{title}" was declined by the buyer.',
  'quote_status.withdrawn': 'Your quote on "{title}" was withdrawn.',
  'quote_status.expired': 'Your quote on "{title}" expired with the request.',
  'quote_status.none': 'You have not quoted on this request yet ("{title}"). Open it from your requests list to quote.',
  'quote_status.not_found': 'I could not find that request under your account. Please share its title as it appears in your list.',
  'quote_status.no_matches': 'You have no matched requests yet. New requests for your categories will appear in your requests list.',
  'rfq_status.open_no_quotes': 'Your request "{title}" is open ({status_label}) with no quotes yet; it stays open until {expires_date}. Matched providers have been notified.',
  'rfq_status.open_quoted': 'Your request "{title}" has {quote_count} of {max_quotes} quotes. Compare them on the request page and accept one to place the order.',
  'rfq_status.accepted': 'Your request "{title}" is accepted — the order is on your orders list.',
  'rfq_status.expired': 'Your request "{title}" expired on {expires_date} without an accepted quote. You can post it again.',
  'rfq_status.cancelled': 'Your request "{title}" is cancelled.',
  'rfq_status.not_found': 'I could not find that request under your account. Please share its title as it appears in your list.',
  'rfq_status.none': 'You have no requests yet. Post one and matched providers will quote.',
  'payment_status.paid': 'Your payment of {amount} for order {order_number} is received and held by AMClub; it is released to the provider only after you accept the work.',
  'payment_status.refunded': 'Your payment for order {order_number} ({amount}) is refunded. It reaches your account within 5–7 working days.',
  'payment_status.refund_pending': 'A refund for order {order_number} is being processed per the policy shown at checkout. It reaches your account within 5–7 working days of processing.',
  'payment_status.not_found': 'I could not find that order under your account. Please share the order number as it appears in your orders list.',
  'payment_status.none': 'You have no payments yet. Payments are made on AMClub at checkout and held until you accept the work.',
  'payout_status.not_due': 'Order {order_number} ({title}) is {status_label}. Your payout ({amount}) is scheduled once the buyer accepts the work.',
  'payout_status.scheduled': 'Your payout of {amount} for order {order_number} is scheduled and goes out in the next payout run to your verified bank account.',
  'payout_status.processing': 'Your payout of {amount} for order {order_number} is processing. It reaches your bank account within 1–2 working days.',
  'payout_status.paid': 'Your payout of {amount} for order {order_number} is paid to your verified bank account.',
  'payout_status.failed': 'Your payout of {amount} for order {order_number} could not be transferred; we retry automatically. Please check your bank details under Earnings.',
  'payout_status.held_dispute': 'Order {order_number} is under dispute, so its payout ({amount}) is on hold until the dispute is resolved (within {sla_days} days).',
  'payout_status.held': 'Your payout of {amount} for order {order_number} is on hold. This happens while bank verification is pending or the account is under review; our team will contact you.',
  'payout_status.not_found': 'I could not find that order under your account. Please share the order number as it appears in your orders list.',
  'payout_status.none': 'You have no completed orders yet, so no payout is due. Payouts go out after the buyer accepts the work.',
  'how_to.create_rfq': 'To post a request: tap "Post a request", pick the category, describe the work (or speak it), add your budget and deadline, and send. Matched, verified providers quote within hours.',
  'how_to.compare_quotes': 'Open your request and tap "Compare": quotes appear side by side with price, delivery and terms. Flags show what differs. Accept the one you prefer.',
  'how_to.accept_quote': 'Open the request, choose a quote and tap "Accept". You pay at checkout; the amount stays with AMClub until you accept the delivered work.',
  'how_to.pay': 'Pay at checkout by UPI, card or net banking through AMClub. The payment is held and released to the provider only after you accept the work.',
  'how_to.refund': 'If you cancel before a provider accepts, you are refunded in full. Other cases follow the refund policy shown at checkout. Refunds reach your account within 5–7 working days.',
  'how_to.cancel': 'Open the order and tap "Cancel". Before the provider accepts, cancellation is free with a full refund; after that, the policy shown at checkout applies.',
  'how_to.verification': 'Every provider is KYC- and credential-verified before their listings go live — look for the blue tick. Verification usually completes within 24 hours of submitting documents.',
  'how_to.fees': 'Providers receive their full amount minus only AMC’s 5% commission. All payment gateway charges are borne by AMC. Buyers pay no fee.',
  'how_to.kyc_bank': 'Under Profile, add your GSTIN or Udyam and your bank account (a penny-drop verification confirms it). Payouts go only to a verified account.',
  'how_to.payout_timing': 'Payouts are scheduled when the buyer accepts the work and go out in the next payout run to your verified bank account, usually within 1–2 working days.',
  'how_to.dispute': 'Open the order and tap "Raise a dispute" with your statement. Both sides are heard; we acknowledge within {sla_hours} hours and resolve within {sla_days} days.',
  'how_to.contact_human': 'You can reach a person at {contact}. We acknowledge within {sla_hours} hours.',
  'how_to.other': 'I can help with orders, quotes, requests, payments, payouts, verification and fees. Tell me which, or ask for a person and I will connect you.',
  'nudge.confirm': 'Shall I send a polite reminder to the other party? They get one message from AMClub asking for an update; you can send one every 24 hours.',
  'nudge.sent': 'Done — a reminder went to the other party. You can send another after 24 hours.',
  'nudge.capped': 'A reminder was already sent in the last {hours} hours. You can send the next one after that.',
  'nudge.no_subject': 'I could not tell which order or request you mean. Please share the order number or the request title.',
  'nudge.out_of_window': 'That order or request is no longer active, so a reminder cannot be sent.',
  'new_need.offer': 'Shall I start a request for this? I will draft it and ask you before anything is sent.',
  greeting: 'Hello! I can help with your orders, quotes, requests, payments and payouts. What would you like to know?',
  capabilities: 'I can help with: your orders and where they stand ("where is my order?"), your requests and the quotes on them ("did I get any quotes?"), payments and refunds ("did my payment go through?"), payouts if you are a provider, and how things work here (cancelling, disputes, fees). You can also ask for a person at any time. What would you like to know?',
  unclear: 'I did not quite get that. You can ask about an order ("where is my order"), a request, a payment or a payout — or ask for a person.',
  unclear_again: 'Sorry, I still did not get that. If you tell me the order number or request title I can check; or say "person" and I will connect you.',
  escalated: 'A person from AMClub will contact you within {sla_hours} hours (ticket {ticket_ref}). You can also reach us at {contact}.',
  escalated_open: 'Your message is added to your open ticket; a person will reply within {sla_hours} hours.',
  resolved: 'Your support ticket is resolved. If anything is still unclear, just write here again.',
}

const hi: Copy = {
  'order_status.placed': 'ऑर्डर {order_number} ({title}) दिया गया और भुगतान हो चुका है। प्रोवाइडर के पास स्वीकार करने के लिए 24 घंटे हैं; न करने पर ऑर्डर रद्द होकर पूरा रिफंड मिलता है।',
  'order_status.accepted': 'ऑर्डर {order_number} ({title}) स्वीकृत है। प्रोवाइडर आपकी आवश्यकताओं की प्रतीक्षा में है या जल्द शुरू करेगा। अपेक्षित तारीख {eta_date}।',
  'order_status.requirements_submitted': 'ऑर्डर {order_number} ({title}): आवश्यकताएं मिल गईं; प्रोवाइडर शुरू करने वाला है। अपेक्षित तारीख {eta_date}।',
  'order_status.in_progress': 'ऑर्डर {order_number} ({title}) प्रगति में है। अपेक्षित तारीख {eta_date}। आपका भुगतान ({amount}) काम स्वीकार करने तक AMClub के पास रहता है।',
  'order_status.delivered': 'ऑर्डर {order_number} ({title}) डिलीवर हो गया। काम देखकर स्वीकार करें या संशोधन माँगें। कुछ न करने पर डिलीवरी के 72 घंटे बाद यह अपने आप पूरा हो जाता है।',
  'order_status.revision_requested': 'ऑर्डर {order_number} ({title}): संशोधन का अनुरोध है और प्रोवाइडर उस पर काम कर रहा है।',
  'order_status.completed': 'ऑर्डर {order_number} ({title}) पूर्ण है। {amount} भुगतान शेड्यूल के अनुसार प्रोवाइडर को जारी होता है।',
  'order_status.reviewed': 'ऑर्डर {order_number} ({title}) पूर्ण और समीक्षित है। धन्यवाद।',
  'order_status.disputed': 'ऑर्डर {order_number} ({title}) विवाद में है। हमारी टीम दोनों पक्ष देखती है; {sla_hours} घंटे में पावती और {sla_days} दिन में निपटारा।',
  'order_status.resolved': 'ऑर्डर {order_number} ({title}) निपट गया: {status_label}। कोई रिफंड 5–7 कार्यदिवसों में आपके खाते में आता है।',
  'order_status.cancelled': 'ऑर्डर {order_number} ({title}) रद्द है ({status_label})। कोई रिफंड 5–7 कार्यदिवसों में आपके खाते में आता है।',
  'order_status.refunded': 'ऑर्डर {order_number} ({title}) का रिफंड हो गया। राशि ({amount}) 5–7 कार्यदिवसों में आपके खाते में आती है।',
  'order_status.not_found': 'आपके खाते में वह ऑर्डर नहीं मिला। कृपया ऑर्डर नंबर वैसे ही भेजें जैसा ऑर्डर सूची में दिखता है।',
  'order_status.none': 'आपका अभी कोई ऑर्डर नहीं है। माँग पोस्ट करें या पैकेज खरीदें, वह यहाँ दिखेगा।',
  'quote_status.submitted': '"{title}" पर आपका कोटेशन ({price}) जमा है और खरीदार को दिख रहा है। माँग पर {max_quotes} में से {quote_count} कोटेशन हैं; यह {expires_date} को समाप्त होगी।',
  'quote_status.accepted': '"{title}" पर आपका कोटेशन स्वीकार हुआ — ऑर्डर आपकी ऑर्डर सूची में है।',
  'quote_status.declined': '"{title}" पर आपका कोटेशन खरीदार ने अस्वीकार किया।',
  'quote_status.withdrawn': '"{title}" पर आपका कोटेशन वापस लिया गया।',
  'quote_status.expired': '"{title}" पर आपका कोटेशन माँग के साथ समाप्त हो गया।',
  'quote_status.none': 'आपने इस माँग ("{title}") पर अभी कोटेशन नहीं दिया। अपनी माँग सूची से खोलकर कोटेशन दें।',
  'quote_status.not_found': 'आपके खाते में वह माँग नहीं मिली। कृपया उसका शीर्षक वैसे ही भेजें जैसा सूची में है।',
  'quote_status.no_matches': 'आपके लिए अभी कोई मिलती-जुलती माँग नहीं है। आपकी श्रेणियों की नई माँगें आपकी माँग सूची में दिखेंगी।',
  'rfq_status.open_no_quotes': 'आपकी माँग "{title}" खुली है ({status_label}), अभी कोई कोटेशन नहीं; यह {expires_date} तक खुली रहेगी। मिलते-जुलते प्रोवाइडरों को सूचना भेज दी गई है।',
  'rfq_status.open_quoted': 'आपकी माँग "{title}" पर {max_quotes} में से {quote_count} कोटेशन हैं। माँग पेज पर तुलना करें और एक स्वीकार कर ऑर्डर दें।',
  'rfq_status.accepted': 'आपकी माँग "{title}" स्वीकृत है — ऑर्डर आपकी ऑर्डर सूची में है।',
  'rfq_status.expired': 'आपकी माँग "{title}" {expires_date} को बिना स्वीकृत कोटेशन के समाप्त हो गई। आप इसे फिर पोस्ट कर सकते हैं।',
  'rfq_status.cancelled': 'आपकी माँग "{title}" रद्द है।',
  'rfq_status.not_found': 'आपके खाते में वह माँग नहीं मिली। कृपया उसका शीर्षक वैसे ही भेजें जैसा सूची में है।',
  'rfq_status.none': 'आपकी अभी कोई माँग नहीं है। एक पोस्ट करें, मिलते-जुलते प्रोवाइडर कोटेशन देंगे।',
  'payment_status.paid': 'ऑर्डर {order_number} के लिए आपका {amount} का भुगतान मिल गया और AMClub के पास सुरक्षित है; काम स्वीकार करने के बाद ही प्रोवाइडर को जारी होता है।',
  'payment_status.refunded': 'ऑर्डर {order_number} का भुगतान ({amount}) वापस कर दिया गया। यह 5–7 कार्यदिवसों में आपके खाते में आता है।',
  'payment_status.refund_pending': 'ऑर्डर {order_number} का रिफंड चेकआउट पर दिखी नीति के अनुसार प्रोसेस हो रहा है। प्रोसेस होने के 5–7 कार्यदिवसों में खाते में आता है।',
  'payment_status.not_found': 'आपके खाते में वह ऑर्डर नहीं मिला। कृपया ऑर्डर नंबर वैसे ही भेजें जैसा ऑर्डर सूची में दिखता है।',
  'payment_status.none': 'आपका अभी कोई भुगतान नहीं है। भुगतान AMClub पर चेकआउट के समय होता है और काम स्वीकार करने तक सुरक्षित रहता है।',
  'payout_status.not_due': 'ऑर्डर {order_number} ({title}) {status_label} है। खरीदार के काम स्वीकार करने पर आपका भुगतान ({amount}) निर्धारित होता है।',
  'payout_status.scheduled': 'ऑर्डर {order_number} के लिए आपका {amount} का भुगतान निर्धारित है और अगले भुगतान चक्र में आपके सत्यापित बैंक खाते में जाएगा।',
  'payout_status.processing': 'ऑर्डर {order_number} के लिए आपका {amount} का भुगतान प्रोसेस हो रहा है। 1–2 कार्यदिवसों में बैंक खाते में पहुँचता है।',
  'payout_status.paid': 'ऑर्डर {order_number} के लिए आपका {amount} का भुगतान आपके सत्यापित बैंक खाते में कर दिया गया।',
  'payout_status.failed': 'ऑर्डर {order_number} के लिए आपका {amount} का भुगतान ट्रांसफर नहीं हो सका; हम अपने आप फिर प्रयास करते हैं। कृपया Earnings में बैंक विवरण जाँचें।',
  'payout_status.held_dispute': 'ऑर्डर {order_number} विवाद में है, इसलिए उसका भुगतान ({amount}) विवाद निपटने तक ({sla_days} दिन में) रोका गया है।',
  'payout_status.held': 'ऑर्डर {order_number} के लिए आपका {amount} का भुगतान रोका गया है। यह बैंक सत्यापन लंबित होने या खाते की समीक्षा के दौरान होता है; हमारी टीम संपर्क करेगी।',
  'payout_status.not_found': 'आपके खाते में वह ऑर्डर नहीं मिला। कृपया ऑर्डर नंबर वैसे ही भेजें जैसा ऑर्डर सूची में दिखता है।',
  'payout_status.none': 'आपका अभी कोई पूर्ण ऑर्डर नहीं है, इसलिए कोई भुगतान देय नहीं। भुगतान खरीदार के काम स्वीकार करने के बाद होता है।',
  'how_to.create_rfq': 'माँग पोस्ट करने के लिए: "माँग पोस्ट करें" दबाएँ, श्रेणी चुनें, काम बताएँ (बोलकर भी), बजट और समय-सीमा जोड़ें और भेजें। सत्यापित प्रोवाइडर कुछ घंटों में कोटेशन देते हैं।',
  'how_to.compare_quotes': 'अपनी माँग खोलकर "तुलना करें" दबाएँ: कोटेशन कीमत, डिलीवरी और शर्तों के साथ आमने-सामने दिखते हैं। अंतर फ़्लैग से दिखता है। पसंदीदा स्वीकार करें।',
  'how_to.accept_quote': 'माँग खोलें, कोटेशन चुनें और "स्वीकार करें" दबाएँ। चेकआउट पर भुगतान करें; राशि काम स्वीकार करने तक AMClub के पास रहती है।',
  'how_to.pay': 'चेकआउट पर AMClub के ज़रिए UPI, कार्ड या नेट बैंकिंग से भुगतान करें। भुगतान सुरक्षित रहता है और काम स्वीकार करने के बाद ही प्रोवाइडर को जारी होता है।',
  'how_to.refund': 'प्रोवाइडर के स्वीकार करने से पहले रद्द करने पर पूरा रिफंड मिलता है। अन्य मामलों में चेकआउट पर दिखी रिफंड नीति लागू होती है। रिफंड 5–7 कार्यदिवसों में खाते में आता है।',
  'how_to.cancel': 'ऑर्डर खोलकर "रद्द करें" दबाएँ। प्रोवाइडर के स्वीकार करने से पहले रद्द करना मुफ़्त है और पूरा रिफंड मिलता है; उसके बाद चेकआउट की नीति लागू होती है।',
  'how_to.verification': 'हर प्रोवाइडर की लिस्टिंग लाइव होने से पहले KYC और क्रेडेंशियल सत्यापन होता है — नीला टिक देखें। दस्तावेज़ जमा करने के 24 घंटे में सत्यापन आमतौर पर पूरा होता है।',
  'how_to.fees': 'प्रोवाइडर को पूरी राशि मिलती है, केवल AMC का 5% कमीशन घटाकर। पेमेंट गेटवे शुल्क AMC वहन करता है। खरीदार कोई शुल्क नहीं देता।',
  'how_to.kyc_bank': 'प्रोफ़ाइल में अपना GSTIN या उद्यम और बैंक खाता जोड़ें (पेनी-ड्रॉप सत्यापन इसकी पुष्टि करता है)। भुगतान केवल सत्यापित खाते में जाता है।',
  'how_to.payout_timing': 'खरीदार के काम स्वीकार करने पर भुगतान निर्धारित होता है और अगले भुगतान चक्र में सत्यापित बैंक खाते में जाता है, आमतौर पर 1–2 कार्यदिवसों में।',
  'how_to.dispute': 'ऑर्डर खोलकर अपने बयान के साथ "विवाद उठाएँ" दबाएँ। दोनों पक्ष सुने जाते हैं; {sla_hours} घंटे में पावती और {sla_days} दिन में निपटारा।',
  'how_to.contact_human': 'आप {contact} पर किसी व्यक्ति से संपर्क कर सकते हैं। हम {sla_hours} घंटे में जवाब देते हैं।',
  'how_to.other': 'मैं ऑर्डर, कोटेशन, माँग, भुगतान, पेआउट, सत्यापन और शुल्क में मदद कर सकता हूँ। बताएँ किसमें, या किसी व्यक्ति से बात करने को कहें।',
  'nudge.confirm': 'क्या मैं दूसरे पक्ष को विनम्र याद दिलाऊँ? उन्हें AMClub से अपडेट माँगता एक संदेश जाएगा; आप हर 24 घंटे में एक भेज सकते हैं।',
  'nudge.sent': 'हो गया — दूसरे पक्ष को याद दिला दी गई। अगली 24 घंटे बाद भेज सकते हैं।',
  'nudge.capped': 'पिछले {hours} घंटों में एक याद दिलाई जा चुकी है। अगली उसके बाद भेज सकते हैं।',
  'nudge.no_subject': 'समझ नहीं आया कि कौन सा ऑर्डर या माँग। कृपया ऑर्डर नंबर या माँग का शीर्षक भेजें।',
  'nudge.out_of_window': 'वह ऑर्डर या माँग अब सक्रिय नहीं है, इसलिए याद नहीं दिलाई जा सकती।',
  'new_need.offer': 'क्या मैं इसके लिए एक माँग शुरू करूँ? मैं ड्राफ्ट बनाऊँगा और कुछ भी भेजने से पहले आपसे पूछूँगा।',
  greeting: 'नमस्ते! मैं आपके ऑर्डर, कोटेशन, माँग, भुगतान और पेआउट में मदद कर सकता हूँ। क्या जानना चाहेंगे?',
  capabilities: 'मैं इनमें मदद कर सकता हूँ: आपके ऑर्डर और उनकी स्थिति ("मेरा ऑर्डर कहाँ है?"), आपकी माँगें और उन पर आए कोटेशन ("क्या कोटेशन आए?"), भुगतान और रिफंड ("क्या मेरा भुगतान हो गया?"), प्रोवाइडर हों तो पेआउट, और यहाँ काम कैसे होता है (रद्द करना, विवाद, शुल्क)। आप कभी भी किसी व्यक्ति से बात करने को कह सकते हैं। क्या जानना चाहेंगे?',
  unclear: 'मैं ठीक से समझ नहीं पाया। आप ऑर्डर ("मेरा ऑर्डर कहाँ है"), माँग, भुगतान या पेआउट के बारे में पूछ सकते हैं — या किसी व्यक्ति को माँगें।',
  unclear_again: 'माफ़ कीजिए, अब भी समझ नहीं पाया। ऑर्डर नंबर या माँग का शीर्षक बताएँ तो देखता हूँ; या "व्यक्ति" लिखें, मैं जोड़ देता हूँ।',
  escalated: 'AMClub से एक व्यक्ति {sla_hours} घंटे में आपसे संपर्क करेगा (टिकट {ticket_ref})। आप {contact} पर भी पहुँच सकते हैं।',
  escalated_open: 'आपका संदेश आपके खुले टिकट में जोड़ दिया गया; एक व्यक्ति {sla_hours} घंटे में जवाब देगा।',
  resolved: 'आपका सपोर्ट टिकट निपट गया। कुछ अब भी अस्पष्ट हो तो यहीं फिर लिखें।',
}

const te: Copy = {
  'order_status.placed': 'ఆర్డర్ {order_number} ({title}) ఇచ్చారు, చెల్లింపు అయింది. ప్రొవైడర్ ఆమోదించడానికి 24 గంటలు ఉన్నాయి; లేకపోతే రద్దు అయి పూర్తి రీఫండ్ వస్తుంది.',
  'order_status.accepted': 'ఆర్డర్ {order_number} ({title}) ఆమోదించారు. ప్రొవైడర్ మీ అవసరాల కోసం వేచి ఉన్నారు లేదా త్వరలో మొదలుపెడతారు. అంచనా తేదీ {eta_date}.',
  'order_status.requirements_submitted': 'ఆర్డర్ {order_number} ({title}): అవసరాలు అందాయి; ప్రొవైడర్ మొదలుపెట్టబోతున్నారు. అంచనా తేదీ {eta_date}.',
  'order_status.in_progress': 'ఆర్డర్ {order_number} ({title}) పనిలో ఉంది. అంచనా తేదీ {eta_date}. మీ చెల్లింపు ({amount}) పని ఆమోదించే వరకు AMClub వద్ద ఉంటుంది.',
  'order_status.delivered': 'ఆర్డర్ {order_number} ({title}) డెలివరీ అయింది. పనిని చూసి ఆమోదించండి లేదా సవరణ కోరండి. ఏమీ చేయకపోతే డెలివరీ తర్వాత 72 గంటలకు ఆటోమేటిక్‌గా పూర్తవుతుంది.',
  'order_status.revision_requested': 'ఆర్డర్ {order_number} ({title}): సవరణ కోరారు, ప్రొవైడర్ దానిపై పని చేస్తున్నారు.',
  'order_status.completed': 'ఆర్డర్ {order_number} ({title}) పూర్తయింది. {amount} చెల్లింపు షెడ్యూల్ ప్రకారం ప్రొవైడర్‌కు విడుదల అవుతుంది.',
  'order_status.reviewed': 'ఆర్డర్ {order_number} ({title}) పూర్తయి సమీక్షించారు. ధన్యవాదాలు.',
  'order_status.disputed': 'ఆర్డర్ {order_number} ({title}) వివాదంలో ఉంది. మా బృందం రెండు వైపులా చూస్తుంది; {sla_hours} గంటల్లో స్వీకృతి, {sla_days} రోజుల్లో పరిష్కారం.',
  'order_status.resolved': 'ఆర్డర్ {order_number} ({title}) పరిష్కారం అయింది: {status_label}. రీఫండ్ ఉంటే 5–7 పని రోజుల్లో మీ ఖాతాకు చేరుతుంది.',
  'order_status.cancelled': 'ఆర్డర్ {order_number} ({title}) రద్దు అయింది ({status_label}). రీఫండ్ ఉంటే 5–7 పని రోజుల్లో మీ ఖాతాకు చేరుతుంది.',
  'order_status.refunded': 'ఆర్డర్ {order_number} ({title}) రీఫండ్ అయింది. మొత్తం ({amount}) 5–7 పని రోజుల్లో మీ ఖాతాకు చేరుతుంది.',
  'order_status.not_found': 'మీ ఖాతాలో ఆ ఆర్డర్ కనిపించలేదు. ఆర్డర్ జాబితాలో ఉన్నట్లే ఆర్డర్ నంబర్ పంపండి.',
  'order_status.none': 'మీకు ఇంకా ఆర్డర్లు లేవు. అభ్యర్థన పోస్ట్ చేయండి లేదా ప్యాకేజీ కొనండి, అది ఇక్కడ కనిపిస్తుంది.',
  'quote_status.submitted': '"{title}" పై మీ కొటేషన్ ({price}) సమర్పించారు, కొనుగోలుదారుకు కనిపిస్తోంది. అభ్యర్థనకు {max_quotes} లో {quote_count} కొటేషన్లు ఉన్నాయి; {expires_date} న గడువు ముగుస్తుంది.',
  'quote_status.accepted': '"{title}" పై మీ కొటేషన్ ఆమోదించారు — ఆర్డర్ మీ ఆర్డర్ జాబితాలో ఉంది.',
  'quote_status.declined': '"{title}" పై మీ కొటేషన్‌ను కొనుగోలుదారు తిరస్కరించారు.',
  'quote_status.withdrawn': '"{title}" పై మీ కొటేషన్ ఉపసంహరించారు.',
  'quote_status.expired': '"{title}" పై మీ కొటేషన్ అభ్యర్థనతో పాటు గడువు ముగిసింది.',
  'quote_status.none': 'ఈ అభ్యర్థనకు ("{title}") మీరు ఇంకా కొటేషన్ ఇవ్వలేదు. మీ అభ్యర్థనల జాబితా నుండి తెరిచి కొటేషన్ ఇవ్వండి.',
  'quote_status.not_found': 'మీ ఖాతాలో ఆ అభ్యర్థన కనిపించలేదు. జాబితాలో ఉన్నట్లే దాని శీర్షిక పంపండి.',
  'quote_status.no_matches': 'మీకు ఇంకా సరిపోలిన అభ్యర్థనలు లేవు. మీ విభాగాల కొత్త అభ్యర్థనలు మీ అభ్యర్థనల జాబితాలో కనిపిస్తాయి.',
  'rfq_status.open_no_quotes': 'మీ అభ్యర్థన "{title}" తెరిచి ఉంది ({status_label}), ఇంకా కొటేషన్లు లేవు; {expires_date} వరకు తెరిచి ఉంటుంది. సరిపోయే ప్రొవైడర్లకు తెలియజేశాం.',
  'rfq_status.open_quoted': 'మీ అభ్యర్థన "{title}" కు {max_quotes} లో {quote_count} కొటేషన్లు ఉన్నాయి. అభ్యర్థన పేజీలో పోల్చి ఒకటి ఆమోదించి ఆర్డర్ ఇవ్వండి.',
  'rfq_status.accepted': 'మీ అభ్యర్థన "{title}" ఆమోదించారు — ఆర్డర్ మీ ఆర్డర్ జాబితాలో ఉంది.',
  'rfq_status.expired': 'మీ అభ్యర్థన "{title}" {expires_date} న ఆమోదించిన కొటేషన్ లేకుండా గడువు ముగిసింది. మళ్లీ పోస్ట్ చేయవచ్చు.',
  'rfq_status.cancelled': 'మీ అభ్యర్థన "{title}" రద్దు అయింది.',
  'rfq_status.not_found': 'మీ ఖాతాలో ఆ అభ్యర్థన కనిపించలేదు. జాబితాలో ఉన్నట్లే దాని శీర్షిక పంపండి.',
  'rfq_status.none': 'మీకు ఇంకా అభ్యర్థనలు లేవు. ఒకటి పోస్ట్ చేయండి, సరిపోయే ప్రొవైడర్లు కొటేషన్ ఇస్తారు.',
  'payment_status.paid': 'ఆర్డర్ {order_number} కోసం మీ {amount} చెల్లింపు అందింది, AMClub వద్ద భద్రంగా ఉంది; పని ఆమోదించిన తర్వాతే ప్రొవైడర్‌కు విడుదల అవుతుంది.',
  'payment_status.refunded': 'ఆర్డర్ {order_number} చెల్లింపు ({amount}) రీఫండ్ అయింది. 5–7 పని రోజుల్లో మీ ఖాతాకు చేరుతుంది.',
  'payment_status.refund_pending': 'ఆర్డర్ {order_number} రీఫండ్ చెక్అవుట్‌లో చూపిన విధానం ప్రకారం ప్రాసెస్ అవుతోంది. ప్రాసెస్ అయిన 5–7 పని రోజుల్లో ఖాతాకు చేరుతుంది.',
  'payment_status.not_found': 'మీ ఖాతాలో ఆ ఆర్డర్ కనిపించలేదు. ఆర్డర్ జాబితాలో ఉన్నట్లే ఆర్డర్ నంబర్ పంపండి.',
  'payment_status.none': 'మీకు ఇంకా చెల్లింపులు లేవు. చెల్లింపులు AMClub లో చెక్అవుట్ వద్ద జరుగుతాయి, పని ఆమోదించే వరకు భద్రంగా ఉంటాయి.',
  'payout_status.not_due': 'ఆర్డర్ {order_number} ({title}) {status_label}. కొనుగోలుదారు పని ఆమోదించాక మీ చెల్లింపు ({amount}) షెడ్యూల్ అవుతుంది.',
  'payout_status.scheduled': 'ఆర్డర్ {order_number} కోసం మీ {amount} చెల్లింపు షెడ్యూల్ అయింది, తదుపరి చెల్లింపు రన్‌లో మీ ధృవీకరించిన బ్యాంక్ ఖాతాకు వెళ్తుంది.',
  'payout_status.processing': 'ఆర్డర్ {order_number} కోసం మీ {amount} చెల్లింపు ప్రాసెస్ అవుతోంది. 1–2 పని రోజుల్లో బ్యాంక్ ఖాతాకు చేరుతుంది.',
  'payout_status.paid': 'ఆర్డర్ {order_number} కోసం మీ {amount} చెల్లింపు మీ ధృవీకరించిన బ్యాంక్ ఖాతాకు చెల్లించాం.',
  'payout_status.failed': 'ఆర్డర్ {order_number} కోసం మీ {amount} చెల్లింపు బదిలీ కాలేదు; మేము ఆటోమేటిక్‌గా మళ్లీ ప్రయత్నిస్తాం. Earnings లో బ్యాంక్ వివరాలు చూడండి.',
  'payout_status.held_dispute': 'ఆర్డర్ {order_number} వివాదంలో ఉంది, కాబట్టి దాని చెల్లింపు ({amount}) వివాదం పరిష్కారం అయ్యే వరకు ({sla_days} రోజుల్లో) నిలిపివేశాం.',
  'payout_status.held': 'ఆర్డర్ {order_number} కోసం మీ {amount} చెల్లింపు నిలిపివేశాం. బ్యాంక్ ధృవీకరణ పెండింగ్ ఉన్నప్పుడు లేదా ఖాతా సమీక్షలో ఉన్నప్పుడు ఇలా జరుగుతుంది; మా బృందం సంప్రదిస్తుంది.',
  'payout_status.not_found': 'మీ ఖాతాలో ఆ ఆర్డర్ కనిపించలేదు. ఆర్డర్ జాబితాలో ఉన్నట్లే ఆర్డర్ నంబర్ పంపండి.',
  'payout_status.none': 'మీకు ఇంకా పూర్తయిన ఆర్డర్లు లేవు, కాబట్టి చెల్లింపు లేదు. కొనుగోలుదారు పని ఆమోదించాక చెల్లింపులు వెళ్తాయి.',
  'how_to.create_rfq': 'అభ్యర్థన పోస్ట్ చేయడానికి: "అభ్యర్థన పోస్ట్ చేయండి" నొక్కి, వర్గం ఎంచుకుని, పని వివరించి (మాట్లాడి కూడా), బడ్జెట్, గడువు జోడించి పంపండి. ధృవీకరించిన ప్రొవైడర్లు కొన్ని గంటల్లో కొటేషన్ ఇస్తారు.',
  'how_to.compare_quotes': 'మీ అభ్యర్థన తెరిచి "పోల్చండి" నొక్కండి: కొటేషన్లు ధర, డెలివరీ, షరతులతో పక్కపక్కన కనిపిస్తాయి. తేడాలు ఫ్లాగ్‌లతో కనిపిస్తాయి. నచ్చినది ఆమోదించండి.',
  'how_to.accept_quote': 'అభ్యర్థన తెరిచి, కొటేషన్ ఎంచుకుని "ఆమోదించు" నొక్కండి. చెక్అవుట్‌లో చెల్లించండి; పని ఆమోదించే వరకు మొత్తం AMClub వద్ద ఉంటుంది.',
  'how_to.pay': 'చెక్అవుట్‌లో AMClub ద్వారా UPI, కార్డ్ లేదా నెట్ బ్యాంకింగ్‌తో చెల్లించండి. చెల్లింపు భద్రంగా ఉండి పని ఆమోదించాకే ప్రొవైడర్‌కు విడుదల అవుతుంది.',
  'how_to.refund': 'ప్రొవైడర్ ఆమోదించే ముందు రద్దు చేస్తే పూర్తి రీఫండ్. ఇతర సందర్భాల్లో చెక్అవుట్‌లో చూపిన రీఫండ్ విధానం వర్తిస్తుంది. రీఫండ్ 5–7 పని రోజుల్లో ఖాతాకు చేరుతుంది.',
  'how_to.cancel': 'ఆర్డర్ తెరిచి "రద్దు" నొక్కండి. ప్రొవైడర్ ఆమోదించే ముందు రద్దు ఉచితం, పూర్తి రీఫండ్; ఆ తర్వాత చెక్అవుట్ విధానం వర్తిస్తుంది.',
  'how_to.verification': 'ప్రతి ప్రొవైడర్ లిస్టింగ్ లైవ్ కావడానికి ముందు KYC, క్రెడెన్షియల్ ధృవీకరణ జరుగుతుంది — నీలి టిక్ చూడండి. పత్రాలు సమర్పించిన 24 గంటల్లో సాధారణంగా పూర్తవుతుంది.',
  'how_to.fees': 'ప్రొవైడర్లకు పూర్తి మొత్తం, AMC 5% కమిషన్ మాత్రమే మినహాయించి. పేమెంట్ గేట్‌వే ఛార్జీలు AMC భరిస్తుంది. కొనుగోలుదారులకు ఫీజు లేదు.',
  'how_to.kyc_bank': 'ప్రొఫైల్‌లో మీ GSTIN లేదా ఉద్యమ్, బ్యాంక్ ఖాతా జోడించండి (పెన్నీ-డ్రాప్ ధృవీకరణ నిర్ధారిస్తుంది). చెల్లింపులు ధృవీకరించిన ఖాతాకే వెళ్తాయి.',
  'how_to.payout_timing': 'కొనుగోలుదారు పని ఆమోదించాక చెల్లింపు షెడ్యూల్ అయి, తదుపరి రన్‌లో ధృవీకరించిన బ్యాంక్ ఖాతాకు వెళ్తుంది, సాధారణంగా 1–2 పని రోజుల్లో.',
  'how_to.dispute': 'ఆర్డర్ తెరిచి మీ ప్రకటనతో "వివాదం లేవనెత్తండి" నొక్కండి. రెండు వైపులా వింటాం; {sla_hours} గంటల్లో స్వీకృతి, {sla_days} రోజుల్లో పరిష్కారం.',
  'how_to.contact_human': 'మీరు {contact} వద్ద ఒక వ్యక్తిని సంప్రదించవచ్చు. {sla_hours} గంటల్లో స్పందిస్తాం.',
  'how_to.other': 'ఆర్డర్లు, కొటేషన్లు, అభ్యర్థనలు, చెల్లింపులు, పేఅవుట్లు, ధృవీకరణ, ఫీజుల్లో సహాయం చేయగలను. ఏది కావాలో చెప్పండి, లేదా వ్యక్తిని అడగండి.',
  'nudge.confirm': 'అవతలి పక్షానికి మర్యాదపూర్వక గుర్తు పంపనా? వారికి AMClub నుండి అప్‌డేట్ అడుగుతూ ఒక సందేశం వెళ్తుంది; 24 గంటలకు ఒకటి పంపవచ్చు.',
  'nudge.sent': 'పూర్తయింది — అవతలి పక్షానికి గుర్తు వెళ్లింది. తదుపరిది 24 గంటల తర్వాత పంపవచ్చు.',
  'nudge.capped': 'గత {hours} గంటల్లో ఇప్పటికే గుర్తు పంపారు. తదుపరిది ఆ తర్వాత పంపవచ్చు.',
  'nudge.no_subject': 'ఏ ఆర్డర్ లేదా అభ్యర్థనో అర్థం కాలేదు. ఆర్డర్ నంబర్ లేదా అభ్యర్థన శీర్షిక పంపండి.',
  'nudge.out_of_window': 'ఆ ఆర్డర్ లేదా అభ్యర్థన ఇప్పుడు యాక్టివ్‌గా లేదు, కాబట్టి గుర్తు పంపలేము.',
  'new_need.offer': 'దీని కోసం ఒక అభ్యర్థన మొదలుపెట్టమంటారా? నేను డ్రాఫ్ట్ చేసి, ఏదైనా పంపే ముందు మిమ్మల్ని అడుగుతాను.',
  greeting: 'నమస్కారం! మీ ఆర్డర్లు, కొటేషన్లు, అభ్యర్థనలు, చెల్లింపులు, పేఅవుట్లలో సహాయం చేయగలను. ఏం తెలుసుకోవాలి?',
  capabilities: 'వీటిలో సహాయం చేయగలను: మీ ఆర్డర్లు, అవి ఎక్కడ ఉన్నాయి ("నా ఆర్డర్ ఎక్కడ?"), మీ అభ్యర్థనలు, వాటికి వచ్చిన కొటేషన్లు ("కొటేషన్లు వచ్చాయా?"), చెల్లింపులు, రీఫండ్‌లు ("నా చెల్లింపు అయిందా?"), మీరు ప్రొవైడర్ అయితే పేఅవుట్లు, ఇక్కడ పనులు ఎలా జరుగుతాయి (రద్దు, వివాదాలు, ఫీజులు). ఎప్పుడైనా వ్యక్తిని అడగవచ్చు. ఏం తెలుసుకోవాలి?',
  unclear: 'సరిగ్గా అర్థం కాలేదు. ఆర్డర్ ("నా ఆర్డర్ ఎక్కడ"), అభ్యర్థన, చెల్లింపు లేదా పేఅవుట్ గురించి అడగవచ్చు — లేదా వ్యక్తిని అడగండి.',
  unclear_again: 'క్షమించండి, ఇప్పటికీ అర్థం కాలేదు. ఆర్డర్ నంబర్ లేదా అభ్యర్థన శీర్షిక చెబితే చూస్తాను; లేదా "వ్యక్తి" అని రాయండి, కలుపుతాను.',
  escalated: 'AMClub నుండి ఒక వ్యక్తి {sla_hours} గంటల్లో మిమ్మల్ని సంప్రదిస్తారు (టికెట్ {ticket_ref}). {contact} వద్ద కూడా చేరుకోవచ్చు.',
  escalated_open: 'మీ సందేశం మీ తెరిచిన టికెట్‌కు జోడించాం; ఒక వ్యక్తి {sla_hours} గంటల్లో స్పందిస్తారు.',
  resolved: 'మీ సపోర్ట్ టికెట్ పరిష్కారం అయింది. ఇంకా ఏదైనా అస్పష్టంగా ఉంటే ఇక్కడే మళ్లీ రాయండి.',
}

const ta: Copy = {
  'order_status.placed': 'ஆர்டர் {order_number} ({title}) செய்யப்பட்டு பணம் செலுத்தப்பட்டது. வழங்குநர் ஏற்க 24 மணி நேரம் உள்ளது; இல்லையெனில் ரத்தாகி முழுத் தொகை திரும்பும்.',
  'order_status.accepted': 'ஆர்டர் {order_number} ({title}) ஏற்கப்பட்டது. வழங்குநர் உங்கள் தேவைகளுக்காகக் காத்திருக்கிறார் அல்லது விரைவில் தொடங்குவார். எதிர்பார்க்கும் தேதி {eta_date}.',
  'order_status.requirements_submitted': 'ஆர்டர் {order_number} ({title}): தேவைகள் கிடைத்தன; வழங்குநர் தொடங்கப் போகிறார். எதிர்பார்க்கும் தேதி {eta_date}.',
  'order_status.in_progress': 'ஆர்டர் {order_number} ({title}) நடைபெறுகிறது. எதிர்பார்க்கும் தேதி {eta_date}. உங்கள் பணம் ({amount}) வேலையை ஏற்கும் வரை AMClub-இடம் இருக்கும்.',
  'order_status.delivered': 'ஆர்டர் {order_number} ({title}) டெலிவரி ஆனது. வேலையைப் பார்த்து ஏற்கவும் அல்லது திருத்தம் கோரவும். எதுவும் செய்யாவிட்டால் டெலிவரிக்கு 72 மணி நேரத்திற்குப் பிறகு தானாக முடியும்.',
  'order_status.revision_requested': 'ஆர்டர் {order_number} ({title}): திருத்தம் கோரப்பட்டு வழங்குநர் அதில் வேலை செய்கிறார்.',
  'order_status.completed': 'ஆர்டர் {order_number} ({title}) முடிந்தது. {amount} பணம் செலுத்தும் அட்டவணைப்படி வழங்குநருக்கு விடுவிக்கப்படும்.',
  'order_status.reviewed': 'ஆர்டர் {order_number} ({title}) முடிந்து மதிப்பாய்வு செய்யப்பட்டது. நன்றி.',
  'order_status.disputed': 'ஆர்டர் {order_number} ({title}) சர்ச்சையில் உள்ளது. எங்கள் குழு இரு தரப்பையும் பார்க்கிறது; {sla_hours} மணி நேரத்தில் ஒப்புகை, {sla_days} நாட்களில் தீர்வு.',
  'order_status.resolved': 'ஆர்டர் {order_number} ({title}) தீர்க்கப்பட்டது: {status_label}. திரும்பப் பணம் இருந்தால் 5–7 வேலை நாட்களில் உங்கள் கணக்கிற்கு வரும்.',
  'order_status.cancelled': 'ஆர்டர் {order_number} ({title}) ரத்தானது ({status_label}). திரும்பப் பணம் இருந்தால் 5–7 வேலை நாட்களில் உங்கள் கணக்கிற்கு வரும்.',
  'order_status.refunded': 'ஆர்டர் {order_number} ({title}) பணம் திரும்பப்பட்டது. தொகை ({amount}) 5–7 வேலை நாட்களில் உங்கள் கணக்கிற்கு வரும்.',
  'order_status.not_found': 'உங்கள் கணக்கில் அந்த ஆர்டர் இல்லை. ஆர்டர் பட்டியலில் உள்ளபடி ஆர்டர் எண்ணை அனுப்பவும்.',
  'order_status.none': 'உங்களுக்கு இன்னும் ஆர்டர்கள் இல்லை. கோரிக்கை பதிவிடுங்கள் அல்லது தொகுப்பை வாங்குங்கள், அது இங்கே தோன்றும்.',
  'quote_status.submitted': '"{title}" மீதான உங்கள் விலைப்புள்ளி ({price}) சமர்ப்பிக்கப்பட்டு வாங்குபவருக்குத் தெரிகிறது. கோரிக்கையில் {max_quotes} இல் {quote_count} விலைப்புள்ளிகள் உள்ளன; {expires_date} அன்று காலாவதி.',
  'quote_status.accepted': '"{title}" மீதான உங்கள் விலைப்புள்ளி ஏற்கப்பட்டது — ஆர்டர் உங்கள் ஆர்டர் பட்டியலில் உள்ளது.',
  'quote_status.declined': '"{title}" மீதான உங்கள் விலைப்புள்ளியை வாங்குபவர் நிராகரித்தார்.',
  'quote_status.withdrawn': '"{title}" மீதான உங்கள் விலைப்புள்ளி திரும்பப் பெறப்பட்டது.',
  'quote_status.expired': '"{title}" மீதான உங்கள் விலைப்புள்ளி கோரிக்கையுடன் காலாவதியானது.',
  'quote_status.none': 'இந்தக் கோரிக்கைக்கு ("{title}") நீங்கள் இன்னும் விலைப்புள்ளி அளிக்கவில்லை. உங்கள் கோரிக்கைப் பட்டியலிலிருந்து திறந்து அளிக்கவும்.',
  'quote_status.not_found': 'உங்கள் கணக்கில் அந்தக் கோரிக்கை இல்லை. பட்டியலில் உள்ளபடி அதன் தலைப்பை அனுப்பவும்.',
  'quote_status.no_matches': 'உங்களுக்கு இன்னும் பொருந்திய கோரிக்கைகள் இல்லை. உங்கள் பிரிவுகளின் புதிய கோரிக்கைகள் உங்கள் கோரிக்கைப் பட்டியலில் தோன்றும்.',
  'rfq_status.open_no_quotes': 'உங்கள் கோரிக்கை "{title}" திறந்துள்ளது ({status_label}), இன்னும் விலைப்புள்ளிகள் இல்லை; {expires_date} வரை திறந்திருக்கும். பொருந்திய வழங்குநர்களுக்குத் தெரிவிக்கப்பட்டது.',
  'rfq_status.open_quoted': 'உங்கள் கோரிக்கை "{title}" க்கு {max_quotes} இல் {quote_count} விலைப்புள்ளிகள் உள்ளன. கோரிக்கைப் பக்கத்தில் ஒப்பிட்டு ஒன்றை ஏற்று ஆர்டர் செய்யுங்கள்.',
  'rfq_status.accepted': 'உங்கள் கோரிக்கை "{title}" ஏற்கப்பட்டது — ஆர்டர் உங்கள் ஆர்டர் பட்டியலில் உள்ளது.',
  'rfq_status.expired': 'உங்கள் கோரிக்கை "{title}" {expires_date} அன்று ஏற்கப்பட்ட விலைப்புள்ளி இல்லாமல் காலாவதியானது. மீண்டும் பதிவிடலாம்.',
  'rfq_status.cancelled': 'உங்கள் கோரிக்கை "{title}" ரத்தானது.',
  'rfq_status.not_found': 'உங்கள் கணக்கில் அந்தக் கோரிக்கை இல்லை. பட்டியலில் உள்ளபடி அதன் தலைப்பை அனுப்பவும்.',
  'rfq_status.none': 'உங்களுக்கு இன்னும் கோரிக்கைகள் இல்லை. ஒன்றைப் பதிவிடுங்கள், பொருந்திய வழங்குநர்கள் விலைப்புள்ளி அளிப்பார்கள்.',
  'payment_status.paid': 'ஆர்டர் {order_number} க்கான உங்கள் {amount} பணம் பெறப்பட்டு AMClub-இடம் பாதுகாப்பாக உள்ளது; வேலையை ஏற்ற பிறகே வழங்குநருக்கு விடுவிக்கப்படும்.',
  'payment_status.refunded': 'ஆர்டர் {order_number} க்கான பணம் ({amount}) திரும்பப்பட்டது. 5–7 வேலை நாட்களில் உங்கள் கணக்கிற்கு வரும்.',
  'payment_status.refund_pending': 'ஆர்டர் {order_number} க்கான திரும்பப் பணம் செக்அவுட்டில் காட்டிய கொள்கைப்படி செயலாக்கப்படுகிறது. செயலாக்கத்திற்கு 5–7 வேலை நாட்களில் கணக்கிற்கு வரும்.',
  'payment_status.not_found': 'உங்கள் கணக்கில் அந்த ஆர்டர் இல்லை. ஆர்டர் பட்டியலில் உள்ளபடி ஆர்டர் எண்ணை அனுப்பவும்.',
  'payment_status.none': 'உங்களுக்கு இன்னும் பணம் செலுத்தல்கள் இல்லை. AMClub-இல் செக்அவுட்டில் பணம் செலுத்தப்பட்டு வேலையை ஏற்கும் வரை பாதுகாக்கப்படும்.',
  'payout_status.not_due': 'ஆர்டர் {order_number} ({title}) {status_label}. வாங்குபவர் வேலையை ஏற்றதும் உங்கள் பணம் ({amount}) திட்டமிடப்படும்.',
  'payout_status.scheduled': 'ஆர்டர் {order_number} க்கான உங்கள் {amount} பணம் திட்டமிடப்பட்டு அடுத்த பணச் சுற்றில் உங்கள் சரிபார்க்கப்பட்ட வங்கிக் கணக்கிற்குச் செல்லும்.',
  'payout_status.processing': 'ஆர்டர் {order_number} க்கான உங்கள் {amount} பணம் செயலாக்கத்தில் உள்ளது. 1–2 வேலை நாட்களில் வங்கிக் கணக்கிற்கு வரும்.',
  'payout_status.paid': 'ஆர்டர் {order_number} க்கான உங்கள் {amount} பணம் உங்கள் சரிபார்க்கப்பட்ட வங்கிக் கணக்கிற்குச் செலுத்தப்பட்டது.',
  'payout_status.failed': 'ஆர்டர் {order_number} க்கான உங்கள் {amount} பணம் மாற்ற முடியவில்லை; நாங்கள் தானாக மீண்டும் முயற்சிக்கிறோம். Earnings இல் வங்கி விவரங்களைச் சரிபார்க்கவும்.',
  'payout_status.held_dispute': 'ஆர்டர் {order_number} சர்ச்சையில் உள்ளதால் அதன் பணம் ({amount}) சர்ச்சை தீரும் வரை ({sla_days} நாட்களில்) நிறுத்தி வைக்கப்பட்டுள்ளது.',
  'payout_status.held': 'ஆர்டர் {order_number} க்கான உங்கள் {amount} பணம் நிறுத்தி வைக்கப்பட்டுள்ளது. வங்கிச் சரிபார்ப்பு நிலுவையில் இருக்கும்போது அல்லது கணக்கு மதிப்பாய்வில் இருக்கும்போது இது நிகழும்; எங்கள் குழு தொடர்பு கொள்ளும்.',
  'payout_status.not_found': 'உங்கள் கணக்கில் அந்த ஆர்டர் இல்லை. ஆர்டர் பட்டியலில் உள்ளபடி ஆர்டர் எண்ணை அனுப்பவும்.',
  'payout_status.none': 'உங்களுக்கு இன்னும் முடிந்த ஆர்டர்கள் இல்லை, எனவே பணம் நிலுவையில் இல்லை. வாங்குபவர் வேலையை ஏற்ற பிறகு பணம் செல்லும்.',
  'how_to.create_rfq': 'கோரிக்கை பதிவிட: "கோரிக்கை பதிவிடு" அழுத்தி, பிரிவைத் தேர்ந்தெடுத்து, வேலையை விவரித்து (பேசியும்), பட்ஜெட், காலக்கெடு சேர்த்து அனுப்புங்கள். சரிபார்க்கப்பட்ட வழங்குநர்கள் சில மணி நேரத்தில் விலைப்புள்ளி அளிப்பார்கள்.',
  'how_to.compare_quotes': 'உங்கள் கோரிக்கையைத் திறந்து "ஒப்பிடு" அழுத்துங்கள்: விலைப்புள்ளிகள் விலை, டெலிவரி, நிபந்தனைகளுடன் அருகருகே தோன்றும். வேறுபாடுகள் கொடிகளால் காட்டப்படும். விரும்பியதை ஏற்கவும்.',
  'how_to.accept_quote': 'கோரிக்கையைத் திறந்து, விலைப்புள்ளியைத் தேர்ந்தெடுத்து "ஏற்கவும்" அழுத்துங்கள். செக்அவுட்டில் பணம் செலுத்துங்கள்; வேலையை ஏற்கும் வரை தொகை AMClub-இடம் இருக்கும்.',
  'how_to.pay': 'செக்அவுட்டில் AMClub மூலம் UPI, கார்டு அல்லது நெட் பேங்கிங்கில் பணம் செலுத்துங்கள். பணம் பாதுகாக்கப்பட்டு வேலையை ஏற்ற பிறகே வழங்குநருக்கு விடுவிக்கப்படும்.',
  'how_to.refund': 'வழங்குநர் ஏற்கும் முன் ரத்து செய்தால் முழுத் தொகை திரும்பும். மற்ற சந்தர்ப்பங்களில் செக்அவுட்டில் காட்டிய கொள்கை பொருந்தும். திரும்பப் பணம் 5–7 வேலை நாட்களில் கணக்கிற்கு வரும்.',
  'how_to.cancel': 'ஆர்டரைத் திறந்து "ரத்து" அழுத்துங்கள். வழங்குநர் ஏற்கும் முன் ரத்து இலவசம், முழுத் தொகை திரும்பும்; அதன் பிறகு செக்அவுட் கொள்கை பொருந்தும்.',
  'how_to.verification': 'ஒவ்வொரு வழங்குநரின் பட்டியலும் லைவ் ஆகும் முன் KYC மற்றும் சான்று சரிபார்ப்பு நடக்கும் — நீல டிக்கைப் பாருங்கள். ஆவணங்களைச் சமர்ப்பித்த 24 மணி நேரத்தில் பொதுவாக முடியும்.',
  'how_to.fees': 'வழங்குநர்களுக்கு முழுத் தொகை, AMC-இன் 5% கமிஷன் மட்டும் கழித்து. பேமெண்ட் கேட்வே கட்டணங்களை AMC ஏற்கிறது. வாங்குபவர்களுக்குக் கட்டணம் இல்லை.',
  'how_to.kyc_bank': 'சுயவிவரத்தில் உங்கள் GSTIN அல்லது உத்யம் மற்றும் வங்கிக் கணக்கைச் சேர்க்கவும் (பென்னி-டிராப் சரிபார்ப்பு உறுதிப்படுத்தும்). பணம் சரிபார்க்கப்பட்ட கணக்கிற்கே செல்லும்.',
  'how_to.payout_timing': 'வாங்குபவர் வேலையை ஏற்றதும் பணம் திட்டமிடப்பட்டு அடுத்த சுற்றில் சரிபார்க்கப்பட்ட வங்கிக் கணக்கிற்குச் செல்லும், பொதுவாக 1–2 வேலை நாட்களில்.',
  'how_to.dispute': 'ஆர்டரைத் திறந்து உங்கள் அறிக்கையுடன் "சர்ச்சை எழுப்பு" அழுத்துங்கள். இரு தரப்பும் கேட்கப்படும்; {sla_hours} மணி நேரத்தில் ஒப்புகை, {sla_days} நாட்களில் தீர்வு.',
  'how_to.contact_human': '{contact} இல் ஒரு நபரைத் தொடர்பு கொள்ளலாம். {sla_hours} மணி நேரத்தில் பதிலளிக்கிறோம்.',
  'how_to.other': 'ஆர்டர்கள், விலைப்புள்ளிகள், கோரிக்கைகள், பணம் செலுத்தல், பணப்பெறுதல், சரிபார்ப்பு, கட்டணங்களில் உதவ முடியும். எது வேண்டும் என்று சொல்லுங்கள், அல்லது ஒரு நபரைக் கேளுங்கள்.',
  'nudge.confirm': 'மற்றொரு தரப்புக்கு பணிவான நினைவூட்டல் அனுப்பட்டுமா? AMClub-இலிருந்து அப்டேட் கேட்கும் ஒரு செய்தி அவர்களுக்குச் செல்லும்; 24 மணி நேரத்திற்கு ஒன்று அனுப்பலாம்.',
  'nudge.sent': 'முடிந்தது — மற்றொரு தரப்புக்கு நினைவூட்டல் சென்றது. அடுத்ததை 24 மணி நேரத்திற்குப் பிறகு அனுப்பலாம்.',
  'nudge.capped': 'கடந்த {hours} மணி நேரத்தில் ஏற்கனவே நினைவூட்டல் அனுப்பப்பட்டது. அடுத்ததை அதன் பிறகு அனுப்பலாம்.',
  'nudge.no_subject': 'எந்த ஆர்டர் அல்லது கோரிக்கை என்று புரியவில்லை. ஆர்டர் எண் அல்லது கோரிக்கைத் தலைப்பை அனுப்பவும்.',
  'nudge.out_of_window': 'அந்த ஆர்டர் அல்லது கோரிக்கை இனி செயலில் இல்லை, எனவே நினைவூட்டல் அனுப்ப முடியாது.',
  'new_need.offer': 'இதற்கு ஒரு கோரிக்கையைத் தொடங்கட்டுமா? நான் வரைவு செய்து, எதையும் அனுப்பும் முன் உங்களிடம் கேட்பேன்.',
  greeting: 'வணக்கம்! உங்கள் ஆர்டர்கள், விலைப்புள்ளிகள், கோரிக்கைகள், பணம் செலுத்தல், பணப்பெறுதலில் உதவ முடியும். என்ன தெரிந்து கொள்ள வேண்டும்?',
  capabilities: 'இவற்றில் உதவ முடியும்: உங்கள் ஆர்டர்களும் அவற்றின் நிலையும் ("என் ஆர்டர் எங்கே?"), உங்கள் கோரிக்கைகளும் அவற்றுக்கு வந்த விலைப்புள்ளிகளும் ("விலைப்புள்ளிகள் வந்ததா?"), பணம் செலுத்தலும் திரும்பப் பணமும் ("என் பணம் செலுத்தப்பட்டதா?"), நீங்கள் வழங்குநர் என்றால் பணப்பெறுதல், இங்கே எப்படிச் செயல்படுகிறது (ரத்து, சர்ச்சைகள், கட்டணங்கள்). எப்போது வேண்டுமானாலும் ஒரு நபரைக் கேட்கலாம். என்ன தெரிந்து கொள்ள வேண்டும்?',
  unclear: 'சரியாகப் புரியவில்லை. ஆர்டர் ("என் ஆர்டர் எங்கே"), கோரிக்கை, பணம் அல்லது பணப்பெறுதல் பற்றிக் கேட்கலாம் — அல்லது ஒரு நபரைக் கேளுங்கள்.',
  unclear_again: 'மன்னிக்கவும், இன்னும் புரியவில்லை. ஆர்டர் எண் அல்லது கோரிக்கைத் தலைப்பைச் சொன்னால் பார்க்கிறேன்; அல்லது "நபர்" என்று எழுதுங்கள், இணைக்கிறேன்.',
  escalated: 'AMClub-இலிருந்து ஒரு நபர் {sla_hours} மணி நேரத்தில் உங்களைத் தொடர்பு கொள்வார் (டிக்கெட் {ticket_ref}). {contact} இலும் அணுகலாம்.',
  escalated_open: 'உங்கள் செய்தி உங்கள் திறந்த டிக்கெட்டில் சேர்க்கப்பட்டது; ஒரு நபர் {sla_hours} மணி நேரத்தில் பதிலளிப்பார்.',
  resolved: 'உங்கள் ஆதரவு டிக்கெட் தீர்க்கப்பட்டது. இன்னும் ஏதேனும் தெளிவில்லை என்றால் இங்கே மீண்டும் எழுதுங்கள்.',
}

export const SUPPORT_COPY: Record<SupportLocale, Copy> = { en, hi, te, ta }

/** Slot names that may appear in the copy; a completeness test asserts nothing else does. */
export const SUPPORT_SLOT_NAMES = ['order_number', 'title', 'status', 'status_label', 'amount', 'eta_date', 'expires_date', 'quote_count', 'max_quotes', 'price', 'hours', 'sla_hours', 'sla_days', 'contact', 'ticket_ref', 'scheduled_for'] as const

export function statusLabel(kind: 'order' | 'rfq' | 'payout', status: string, locale: SupportLocale): string {
  const table = kind === 'order' ? ORDER_STATUS_LABELS : kind === 'rfq' ? RFQ_STATUS_LABELS : PAYOUT_STATUS_LABELS
  return table[locale][status] ?? table.en[status] ?? status
}

/** Fill `{slots}`; unknown / empty slots render as an empty string (never a placeholder). */
export function renderSupportReply(key: SupportReplyKey, slots: Record<string, string | number>, locale: SupportLocale): string {
  const template = SUPPORT_COPY[locale][key] ?? SUPPORT_COPY.en[key]
  return template
    .replace(/\{([a-z_]+)\}/g, (_, name: string) => {
      const v = slots[name]
      return v === undefined || v === null ? '' : String(v)
    })
    .replace(/\(\)/g, '')
    .replace(/  +/g, ' ')
    .trim()
}
